spring.application.name=spring-boot-demo

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/keystone_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true